# Generated by Django 5.0.4 on 2024-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
