# Generated by Django 5.0.4 on 2024-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='name',
        ),
        migrations.AddField(
            model_name='passenger',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
